extends:
    [
        'stylelint-config-standard',
        'stylelint-config-prettier',
        'stylelint-prettier/recommended',
    ]
plugins: ['stylelint-scss']
overrides: [{ files: ['**/*.scss'], customSyntax: 'postcss-scss' }]